image: node:8.9.4

stages:
  - install
  - test

installation:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - ./node_modules
    expire_in: 1 week

lint:
  stage: test
  dependencies:
    - installation
  script:
    - yarn run lint:err

test:
  stage: test
  dependencies:
    - installation
  script:
    - yarn run test